---
- hosts: servers
  tasks:
    # Refactor this task to install the httpd package using a variable named `yum_package`
    - name: Install httpd
      yum:
        name: httpd
        state: latest
      become: yes
      notify: "Restart web services"

    # Refactor this task to copy index.html to a destination defined by the variable `deploy_path`
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/
      become: yes
    - name: Enable httpd service
      service:
        name: httpd
        enabled: yes
      become: yes

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
      become: yes
      listen: "Restart web services"