---
- hosts: servers
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
      become: yes
      notify: "Restart web services"
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/
      become: yes

  handlers:
    # This handler does 2 things; it enables the httpd service so that when the server is rebooted,
    # httpd will start up, and it restarts the httpd service. Modify this handler so that it only
    # restarts the service, and create a task above to ensure that the httpd service is enabled.
    - name: Restart httpd
      service:
        name: httpd
        enabled: yes
        state: restarted
      become: yes
      listen: "Restart web services"