---
- hosts: servers
  tasks:
    - name: Install httpd
      yum:
        name: "{{ yum_package.name }}"
        state: "{{ yum_package.state }}"
      become: yes
      notify: "Restart web services"

    - name: Copy index.html
      copy:
        src: index.html
        dest: "{{ deploy_path }}"
      become: yes

    - name: Enable httpd service
      service:
        name: httpd
        enabled: yes
      become: yes

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
      become: yes
      listen: "Restart web services"
