---
- hosts: servers
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
      become: yes
      notify: "Restart web services"
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/
      become: yes
    # this task only ensures that the httpd service is enabled, and does not
    # start/stop/restart the service.
    - name: Enable httpd service
      service:
        name: httpd
        enabled: yes
      become: yes

  handlers:
    # This handler now only restarts the service when it is notified, and is
    # not relied upon to make sure the service is enabled.
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
      become: yes
      listen: "Restart web services"